<a href="https://colab.research.google.com/github/ann-e888/Neural-Networks---Pytorch-Lightning/blob/main/tensor_math.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import torch
import numpy as np

In [ ]:
tensor_a = torch.tensor([1,2,3,4])
tensor_b = torch.tensor([5,6,7,8])

In [ ]:
tensor_a + tensor_b

tensor([ 6,  8, 10, 12])

In [ ]:
torch.add(tensor_a, tensor_b)

tensor([ 6,  8, 10, 12])

In [ ]:
tensor_a - tensor_b

tensor([-4, -4, -4, -4])

In [ ]:
torch.sub(tensor_b, tensor_a)

tensor([4, 4, 4, 4])

In [ ]:
tensor_a * tensor_b

tensor([ 5, 12, 21, 32])

In [ ]:
torch.mul(tensor_a, tensor_b)

tensor([ 5, 12, 21, 32])

In [ ]:
tensor_b / tensor_a

tensor([5.0000, 3.0000, 2.3333, 2.0000])

In [ ]:
torch.div(tensor_b, tensor_a)

tensor([5.0000, 3.0000, 2.3333, 2.0000])

In [ ]:
tensor_b % tensor_a

tensor([0, 0, 1, 0])

In [ ]:
torch.remainder(tensor_b, tensor_a)

tensor([0, 0, 1, 0])

In [ ]:
tensor_a ** tensor_b

tensor([    1,    64,  2187, 65536])

In [ ]:
torch.pow(tensor_a, tensor_b)

tensor([    1,    64,  2187, 65536])

In [ ]:
tensor_a.add(tensor_b)

tensor([ 6,  8, 10, 12])

In [ ]:
# Reassignment

tensor_a + tensor_b

tensor([ 6,  8, 10, 12])

In [ ]:
tensor_a

tensor([1, 2, 3, 4])

In [ ]:
tensor_a.add_(tensor_b)

tensor([ 6,  8, 10, 12])

In [ ]:
tensor_a

tensor([ 6,  8, 10, 12])