<a href="https://colab.research.google.com/github/ann-e888/Neural-Networks---Pytorch-Lightning/blob/main/tensors.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import torch
import numpy as np

## Lists

In [ ]:
my_list =[ [3,4,46],[5,6,78],[5,78,9]]
my_list

[[3, 4, 46], [5, 6, 78], [5, 78, 9]]

## Nupmy Array

In [ ]:
np1 = np.random.rand(3,4)
np1

array([[0.42901278, 0.73863731, 0.18666287, 0.7246952 ],
       [0.15425977, 0.70702851, 0.67717018, 0.36082611],
       [0.29705681, 0.99223584, 0.58376403, 0.12887476]])

In [ ]:
np1.dtype

dtype('float64')

## Tensors

In [ ]:
tensor_2d = torch.randn(3,4)
tensor_2d

tensor([[ 0.4869,  0.8210,  1.2558, -0.7101],
        [ 0.7204, -1.9097,  0.3156, -0.0713],
        [-0.7715,  0.0347,  0.4217,  0.2440]])

In [ ]:
tensor_2d.dtype

torch.float32

In [ ]:
tensor_3d = torch.zeros(2,3,4)
tensor_3d

tensor([[[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]],

        [[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]]])

In [ ]:
my_tensor = torch.tensor(np1)
my_tensor

tensor([[0.4290, 0.7386, 0.1867, 0.7247],
        [0.1543, 0.7070, 0.6772, 0.3608],
        [0.2971, 0.9922, 0.5838, 0.1289]], dtype=torch.float64)